# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: nginx-deployment
  replicaCount: 1
  image:
    app: nginx
    version: latest

service:
  name: nginx-service
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32212